name: build

on:
  push:
    branches:
    - '*'
  pull_request:
    branches: 
    - master
  workflow_call:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install zip
      uses: montudor/action-zip@v1        

    - name: Cache Go modules packages
      uses: actions/cache@v2.1.7
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build
      run: GOOS=linux GOARCH=amd64 go build -v -o bin/aws-asg-dyndns-linux-amd64 main.go

    - name: get gomock & mockgen
      run: |
        go get github.com/golang/mock/gomock 
        go get github.com/golang/mock/mockgen
        go install github.com/golang/mock/mockgen

    - name: Generate mocks
      run: GOOS=linux go generate ./...

    - name: Test
      run: go test -v ./...

    - name: Zip output
      run: zip -qq aws-asg-dyndns-linux-amd64.zip aws-asg-dyndns-linux-amd64
      working-directory: bin/

    - name: Checksums
      run: |
        for f in *; do
          sha256sum $f | cut -d ' ' -f 1 > $f.sha256
        done
      working-directory: bin/

    - uses: actions/upload-artifact@v3
      if: github.event_name == 'push' && github.ref_type == 'tag'
      with:
        name: aws-asg-dyndns-binaries
        path: bin/aws-asg-dyndns-linux-amd64*
        if-no-files-found: error
