name: Pre release

on:
  push:
    branches:
      - "master"

jobs:
  build:
    uses: ./.github/workflows/build-app.yaml

  pre-release:
    needs: 
    - build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v3
      with:
        name: aws-asg-dyndns-${{ github.ref_name }}-linux-amd64
        path: bin/

    - uses: "marvinpinto/action-automatic-releases@v1.2.1"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Release latest"
        files: |
          bin/aws-asg-dyndns-${{ github.ref_name }}-linux-amd64
